/* ═══════════════════════════════════════════════════════════════════
   JÚLIO CALIBERDA · PORTFÓLIO · dados dos projetos
   Cada projeto aponta para a animação dele (gen, em specimens.js) e
   para o tema de cores do próprio produto (p, em style.css).
   ═══════════════════════════════════════════════════════════════════ */
window.PORTFOLIO = (function () {
  'use strict';

  const CATEGORIES = {
    saas: 'SaaS & Negócios',
    tools: 'Ferramentas & Automação',
    games: 'Jogos & Mods',
    sites: 'Sites & Hubs',
    labs: 'Experimentos',
  };

  const PROJECTS = [
    {
      id: 'financial-kali', name: 'Financial Kali', sub: 'Financial-Pro', category: 'saas',
      gen: 'kaliChart', p: 'kali', visibility: 'private', repoSlug: 'Financial-Kali-Showcase',
      deploy: 'https://kali.caliberda.com.br',
      desc: 'Ecossistema de gestão financeira pessoal "Obsidian Dark", com IA de voz e visão (Finn IA), multi-empresa e apps Web + Android nativos sobre Firebase.',
      tags: ['React 19', 'Firebase', 'React Native', 'Groq + Gemini'],
      highlights: [
        'Ecossistema completo em produção: web e Android nativo sobre a mesma base Firebase, cobrindo o ciclo financeiro inteiro, do lançamento e da baixa ao parcelamento e ao BI.',
        'Finn IA: assistente com voz (Groq Whisper-large-v3) e visão, com rotação resiliente de API Keys.',
        'Multi-empresa: bases isoladas (Pessoal, Empresa, Projetos) com replicação de categorias.',
        'BI financeiro: fluxo de caixa, evolução de patrimônio e 6 KPIs com variação mês a mês.',
        'Modo Stealth, Google Identity Sync e zero chaves hardcoded para privacidade em primeiro lugar.',
        'Código proprietário, com repositório showcase público para apresentação do produto.',
      ],
      stack: 'React 19 · Vite 8 · Tailwind · Firebase (Firestore + Auth) · Groq (Llama 3.3 70B + Whisper v3) · Gemini 1.5 Flash · React Native 0.81.5 · Expo SDK 54 · NativeWind v4 · EAS Build',
      created: '2026-04-03',
    },
    {
      id: 'pmtt', name: 'Product Manager Time Tracker', sub: 'PMTT', category: 'saas',
      gen: 'pmtt', p: 'pmtt', visibility: 'public', repoSlug: 'Product-Manager-Timer-Tracker',
      deploy: 'https://pmtt.caliberda.com.br',
      desc: 'Gestão de tempo para PMs: cronômetro em tempo real por categoria, dashboards com evidências e exportação em PDF para justificar prioridades.',
      tags: ['Next.js', 'Firebase', 'Recharts', 'Chrome Extension'],
      highlights: [
        'Transforma o trabalho invisível de um PM em evidência: o tempo registrado vira dashboard e PDF que sustentam decisão de prioridade e de carga de trabalho.',
        'Cronômetro calculado pelo servidor (sobrevive a refresh), com atalhos de teclado e pausa com desconto de tempo.',
        'Página "Hoje" com blocos coloridos por categoria e lacunas clicáveis.',
        'Dashboard com heatmap semana × hora, KPIs comparativos e exportação em PDF com resumo executivo.',
        'Categorias totalmente customizáveis, com ícone, cor e atalho de teclado; extensão Chrome publicada.',
      ],
      stack: 'Next.js (App Router, TS) · Firebase (Auth + Firestore) · Tailwind · shadcn/ui · Recharts · react-hook-form · zod · date-fns · Vercel',
      created: '2026-07-02',
    },
    {
      id: 'cardapio', name: 'Cardápio Digital', sub: 'Painel de gestão e totem de autoatendimento', category: 'saas',
      gen: 'eatz', p: 'eatz', visibility: 'private', repoSlug: null,
      deploy: 'https://cardapio.caliberda.com.br',
      desc: 'Sistema completo para restaurantes: cardápio digital multi-tenant, painel de gestão e um totem de autoatendimento em tablet, todos integrados a uma API própria.',
      tags: ['Next.js 16', 'React 19', 'NestJS', 'Flutter'],
      highlights: [
        'Cobre a operação inteira de um restaurante em um só sistema: o pedido entra pelo cardápio ou pelo totem e segue até o KDS e o caixa, eliminando a digitação manual entre salão e cozinha.',
        'Cardápio com busca em tempo real, badges de promoção, carrinho lateral, checkout e status do pedido.',
        'Painel de gestão com login, kanban de pedidos, delivery em tempo real, KDS, caixa e relatórios.',
        'Totem de autoatendimento em Flutter para tablets, com vínculo por QR Code e customização avançada de produtos.',
        'Acesso multi-tenant via token de empresa, com troca de empresa ativa direto no painel.',
        'O maior projeto do acervo, com roadmap de WebSocket e impressão de comandas.',
      ],
      stack: 'Next.js 16 · React 19 · TS 5.7 · Tailwind 4 · shadcn/ui · Sonner · jose (JWT) · NestJS + PostgreSQL (API) · Flutter (Dart) · Riverpod',
      created: '2026-06-24',
    },
    {
      id: 'hotel-pms', name: 'Hotel PMS', sub: 'Módulo de check-in', category: 'saas',
      gen: 'hotel', p: 'hotel', visibility: 'private', repoSlug: null,
      deploy: 'https://modal.caliberda.com.br',
      desc: 'Módulo de check-in de um PMS hoteleiro com UX premium: modal em tela cheia no mobile, seções navegáveis por ScrollSpy e FNRH digital completo.',
      tags: ['React 18', 'Vite', 'TanStack Query', 'Zod'],
      highlights: [
        'Dez seções: hospedagem, faturamento, acompanhantes, tarifas, recebimentos, refeições, veículos, extras, pulseiras e anexos.',
        'FNRH Digital completo com CEP automático via ViaCEP e autocompletar por teclado.',
        'Financeiro com estados de troco, em aberto e quitado, com design system documentado.',
        'Deploy automático via GitHub Actions direto para GitHub Pages.',
      ],
      stack: 'React 18 + Vite · TypeScript · Tailwind 3.4 · shadcn/Radix · TanStack Query · React Hook Form + Zod · React Router',
      created: '2026-03-26',
    },
    {
      id: 'flowvoice', name: 'FlowVoice', sub: 'Flow-Voice', category: 'tools',
      gen: 'flowvoice', p: 'flowvoice', visibility: 'public', repoSlug: 'Flow-Voice',
      deploy: 'https://flowvoice.caliberda.com.br',
      desc: 'Utilitário de bandeja para Windows e Ubuntu que dita texto por voz em qualquer campo do sistema, com polimento, tradução e busca por voz.',
      tags: ['Python', 'PySide6', 'Whisper local', 'PyInstaller'],
      highlights: [
        'Elimina a digitação em qualquer campo do sistema: ditado global no Windows e no Ubuntu, com transcrição rodando offline.',
        'Atalho global de ditado, com modos de polimento de texto e tradução por voz para vários idiomas.',
        'Pesquisa web por voz com chat interativo e failover automático entre provedores de IA.',
        'Transcrição totalmente offline via Whisper local, funcionando mesmo sem internet.',
        'Empacotado como instalador nativo para Windows e pacote .deb para Ubuntu.',
      ],
      stack: 'Python 3.10+ · PySide6 · sounddevice · pynput · Whisper local · PyInstaller · Inno Setup',
      created: '2026-06-07',
    },
    {
      id: 'stg', name: 'Semantic Tab Grouper', sub: 'Extensão de navegador', category: 'tools',
      gen: 'stg', p: 'stg', visibility: 'public', repoSlug: 'Semantic-Tab-Grouper',
      deploy: 'https://stg.caliberda.com.br',
      desc: 'Extensão de navegador que agrupa abas pelo assunto do conteúdo, não só pelo domínio, com um modelo rodando inteiramente no navegador, sem backend.',
      tags: ['Vite', 'Transformers.js', 'WASM', 'Manifest V3'],
      highlights: [
        'Extrai o conteúdo principal da página e gera um embedding para comparar o assunto entre abas.',
        'Modos de agrupamento semantic, domain e hybrid, conforme a preferência do usuário.',
        'Privacidade total: processamento local, zero telemetria, sem enviar dados de navegação.',
        'Compatível com os principais navegadores baseados em Chromium.',
      ],
      stack: 'Vite + @crxjs/vite-plugin · @xenova/transformers · @mozilla/readability',
      created: '2026-07-12',
    },
    {
      id: 'cnpj', name: 'CNPJ API', sub: 'ccnpj', category: 'tools',
      gen: 'cnpj', p: 'cnpj', visibility: 'public', repoSlug: 'ccnpj',
      deploy: 'https://ccnpj.caliberda.com.br',
      desc: 'API REST para consulta de dados cadastrais de empresas brasileiras via CNPJ, agregando múltiplas fontes em um único endpoint JSON.',
      tags: ['FastAPI', 'Python', 'Vercel Serverless'],
      highlights: [
        'Endpoint único que normaliza a pontuação do CNPJ automaticamente.',
        'Agrega múltiplas fontes públicas: razão social, QSA, CNAEs, regime tributário e situação cadastral.',
        'Deploy serverless, simples de rodar tanto na nuvem quanto localmente.',
      ],
      stack: 'FastAPI · Requests · Vercel Serverless',
      created: '2026-06-02',
    },
    {
      id: 'csskins', name: 'CSGO-Skins Inspector', sub: 'Extensão Chrome', category: 'tools',
      gen: 'skins', p: 'skins', visibility: 'private', repoSlug: null,
      deploy: 'https://csskins.caliberda.com.br',
      desc: 'Extensão Chrome (MV3) para o csgo-skins.com. Em cada skin, botões para inspecionar no CS2 via gen link (sem servidor) e ver o preço em R$ direto do Mercado da Steam.',
      tags: ['Manifest V3', 'JavaScript', 'Steam'],
      highlights: [
        'Inspecionar no CS2: abre o jogo com a skin em mãos, no desgaste certo, via gen link montado na própria extensão.',
        'Preço do Mercado da Steam em R$ direto no popover, sem sair do site.',
        'Cards com várias variantes (Factory New, StatTrak e afins) ganham um popover com valor e ações de cada uma.',
        'Seletores do site isolados num único arquivo, com fallback heurístico para sobreviver a mudanças de layout.',
      ],
      stack: 'Chrome Extension (Manifest V3) · JavaScript · Protobuf + CRC32 (gen link) · Steam Market',
      created: '2026-07-14',
    },
    {
      id: 'afotica', name: 'Afótica', sub: 'Jogo de exploração', category: 'games',
      gen: 'afotica', p: 'afotica', visibility: 'public', repoSlug: 'Afotica',
      deploy: 'https://afotica.caliberda.com.br',
      desc: '"Onde a luz não chega, o som enxerga." Você desce uma caverna abissal onde o mundo só existe quando um som o atravessa, e cada eco te denuncia aos predadores.',
      tags: ['WebGL2', 'GLSL', 'Web Audio API', 'Puppeteer'],
      highlights: [
        'Resolve a equação de onda de verdade na GPU, simulando a propagação do som em tempo real.',
        'Predadores ouvem no mesmo instante em que a onda chega, com audição sincronizada à imagem.',
        'Cavernas geradas de forma procedural, com áudio inteiramente sintetizado.',
        'Roda até em arquivo local, sem servidor, com uma suíte própria de testes automatizados.',
      ],
      stack: 'WebGL2 (GLSL) · Canvas2D · Web Audio API · JavaScript vanilla · Puppeteer (testes)',
      created: '2026-07-05',
    },
    {
      id: 'kessler', name: 'Kessler Cascade', sub: 'Arena shooter roguelike', category: 'games',
      gen: 'kessler', p: 'kessler', visibility: 'public', repoSlug: 'Kessler-Cascade',
      deploy: 'https://kessler.caliberda.com.br',
      desc: '"Você não tem armas, a gravidade é a sua arma." Arena shooter roguelike onde você captura inimigos e asteroides em órbita e os arremessa de volta.',
      tags: ['WebGL2', 'Shaders', 'Procedural Audio'],
      highlights: [
        'Renderizador próprio, capaz de milhares de sprites em uma única chamada de desenho.',
        'Lente gravitacional simulada em shader, distorcendo a imagem ao redor de cada poço de gravidade.',
        'Dezenas de inimigos e milhares de partículas em tela sem perder fluidez.',
        'Upgrades por raridade, chefe a cada onda e trilha sonora generativa.',
      ],
      stack: 'WebGL2 · GLSL Shaders · JavaScript vanilla (sem bundler) · Web Audio API',
      created: '2026-07-05',
    },
    {
      id: 'neonstrike', name: 'Neon Strike', sub: 'Arcade cyberpunk', category: 'games',
      gen: 'neon', p: 'neon', visibility: 'private', repoSlug: null,
      deploy: 'https://neonstrike.caliberda.com.br',
      desc: 'Arcade de sobrevivência cyberpunk com evolução de nave, dificuldade progressiva e ranking global em tempo real.',
      tags: ['Canvas API', 'Vanilla JS', 'Firebase RTDB'],
      highlights: [
        'Engine e física próprias, renderizadas em Canvas.',
        'Trilha sonora e efeitos sintetizados, sem nenhum arquivo de áudio externo.',
        'Ranking global em tempo real, compartilhado entre todos os jogadores.',
        'Aplicação leve, em um único arquivo, sem dependências externas.',
      ],
      stack: 'HTML5 Canvas · Vanilla JS ES6+ · Tailwind (CDN) · Web Audio API · Firebase RTDB',
      created: '2026-05-12',
    },
    {
      id: 'cs2mix', name: 'CS2 Mix Balancer', sub: 'Lobby multiplayer', category: 'games',
      gen: 'cs2mix', p: 'cs2mix', visibility: 'private', repoSlug: null,
      deploy: 'https://www.caliberda.com.br/cs2mix',
      desc: 'Organizador de partidas de CS2 com balanceamento matemático de times e um coach com IA que estima probabilidade de vitória.',
      tags: ['Firebase', 'Gemini 2.5', 'Vanilla JS'],
      highlights: [
        'Balanceamento automático buscando a menor diferença de nível médio entre os times.',
        'Coach com IA que estima a chance de vitória e sugere ajustes táticos em tempo real.',
        'Multiplayer em tempo real, com painel administrativo embutido e formatação pronta para compartilhar.',
      ],
      stack: 'HTML5 · JS ES6+ · Tailwind (CDN) · Firebase · Gemini 2.5 Flash (REST) · FontAwesome',
      created: '2026-05-09',
    },
    {
      id: 'allayfriend', name: 'AllayFriend', sub: 'Mod de Minecraft', category: 'games',
      gen: 'allay', p: 'allay', visibility: 'private', repoSlug: null,
      deploy: 'https://allayfriend.caliberda.com.br',
      desc: 'Mod de Minecraft que adiciona companheiros de IA na forma de Allays: cada um com nome, personalidade e vínculo próprio. Obedece ordens pelo chat e a IA roda embutida no mod.',
      tags: ['NeoForge', 'Java', 'IA local'],
      highlights: [
        'Companheiros com nome, personalidade e vínculo próprio com o jogador.',
        'Recebe ordens em linguagem natural pelo chat do jogo.',
        'A IA roda embutida no mod, sem depender de servidor externo.',
        'Site próprio com download, guia e demonstrações.',
      ],
      stack: 'NeoForge · Java · IA local · HTML, CSS e JS (site)',
      created: '2026-09-07',
    },
    {
      id: 'minecraft', name: 'Minecraft Modpack', sub: 'HotDorgs', category: 'games',
      gen: 'voxel', p: 'voxel', visibility: 'private', repoSlug: null,
      deploy: 'https://minecraft.caliberda.com.br',
      desc: 'Landing page para um modpack de Minecraft, com terreno voxel procedural animado em canvas, tutoriais e download direto.',
      tags: ['Vanilla JS', 'Lenis', 'CSS3'],
      highlights: [
        'Terreno voxel procedural animado, renderizado direto em canvas.',
        'Tutoriais separados por tipo de instalação, com vídeo integrado.',
        'Rolagem suave e tipografia temática, reforçando a identidade do modpack.',
      ],
      stack: 'HTML5 · CSS3 (animações) · Vanilla JS · Lenis · Vercel',
      created: '2026-05-10',
    },
    {
      id: 'karolzk', name: 'karolzk', sub: 'Creator Hub B2C', category: 'sites',
      gen: 'live', p: 'karol', visibility: 'private', repoSlug: null,
      deploy: 'https://karolzk.com.br',
      desc: 'Creator Hub B2C para a criadora Karol ZK: um linktree avançado com streaming integrado, parte de uma linha de hubs de criadores.',
      tags: ['JavaScript', 'Streaming'],
      highlights: [
        'Linktree avançado com streaming integrado para a audiência da criadora.',
        'Parte da mesma linha de produto do Titonverso, um modelo de hub reutilizável entre criadores.',
      ],
      stack: 'JavaScript · HTML5/CSS3',
      created: '2026-05-16',
    },
    {
      id: 'titonverso', name: 'Titonverso', sub: 'Creator Hub B2C', category: 'sites',
      gen: 'live', p: 'isa', visibility: 'private', repoSlug: null,
      deploy: 'https://isatiton.com.br',
      desc: 'Creator Hub B2C para a streamer Isa Titon: identidade visual de HUD esports, com painel admin, giveaways, sorteios e ranking de parceiros.',
      tags: ['JavaScript', 'Firebase', 'HUD Design'],
      highlights: [
        'Linguagem visual de HUD esports, com cantos chanfrados e cor de destaque editável via painel admin.',
        'Módulos de giveaway, status ao vivo e integração com as redes sociais da criadora.',
        'Uma das referências de estilo usadas numa versão anterior deste portfólio.',
      ],
      stack: 'JavaScript vanilla · CSS3 · Firebase',
      created: '2026-05-16',
    },
    {
      id: 'caliberda-home', name: 'Caliberda Home', sub: 'caliberda-home', category: 'sites',
      gen: 'hub', p: null, visibility: 'private', repoSlug: null,
      deploy: 'https://www.caliberda.com.br',
      desc: 'Hub central do ecossistema Caliberda: o ponto de entrada que conecta todos os outros produtos e domínios em um único endereço.',
      tags: ['HTML5', 'Canvas'],
      highlights: [
        'Página única que atua como hub central do ecossistema.',
        'Conecta os subdomínios de todos os outros produtos, como Financial Kali, CS2 Mix e Minecraft.',
        'Retrato em meio-tom desenhado em canvas e uma animação própria para cada produto.',
      ],
      stack: 'HTML5/CSS3 · JavaScript · Canvas 2D',
      created: '2026-05-09',
    },
    {
      id: 'script-index', name: 'Script Index', sub: 'Bancada de testes', category: 'sites',
      gen: 'sandbox', p: 'sandbox', visibility: 'private', repoSlug: null,
      deploy: 'https://script.caliberda.com.br',
      desc: 'Bancada de testes para validar scripts em HTML antes de levá-los a um produto com nome próprio.',
      tags: ['HTML'],
      highlights: ['Ambiente isolado para prototipar e validar scripts antes da produção.'],
      stack: 'HTML',
      created: '2026-05-28',
    },
    {
      id: 'temperamentos', name: 'Os Quatro Temperamentos', sub: 'Teste de autoconhecimento', category: 'labs',
      gen: 'temper', p: 'temper', visibility: 'private', repoSlug: null,
      deploy: 'https://qt.caliberda.com.br',
      desc: 'Teste de autoconhecimento que mapeia seu temperamento em dois eixos. Resultado com margem de erro e nada sai do navegador: sem cadastro, sem servidor.',
      tags: ['JS puro', 'Local-first', 'Psicometria'],
      highlights: [
        'Banco de 128 itens; cada sessão sorteia 40, 64 ou 88.',
        'Quatro formatos de resposta, porque cada um erra de um jeito diferente.',
        'Resultado com porcentagem dos quatro, margem de erro, posição no mapa e facetas de nuance.',
        'Pares de consistência e correção de aquiescência para pegar quem responde no automático.',
        '100% front-end: sem backend, sem banco, sem cookies, sem analytics.',
      ],
      stack: 'HTML · CSS · JavaScript puro · Vercel',
      created: '2026-08-06',
    },
    {
      id: 'iaorhuman', name: 'iaorhuman', sub: 'IA ou humano?', category: 'labs',
      gen: 'iaorhuman', p: 'iaorhuman', visibility: 'private', repoSlug: null,
      deploy: null,
      desc: 'Experimento em estágio inicial: um jogo de deslizar cartas para adivinhar se um conteúdo foi feito por IA ou por uma pessoa.',
      tags: ['React', 'Vite', 'TypeScript'],
      highlights: ['Repositório recém-iniciado, um experimento em andamento.'],
      stack: 'TypeScript · React · Vite',
      created: '2026-07-12',
    },
  ];

  return { CATEGORIES, PROJECTS };
})();
